### ISSUE TITLE
StackOverflowError in finding paths

### ISSUE THREAD

**Issue by jesseeichar** [jesseeichar/scala-io#38]
Running this:

``` scala
import scalax.file.Path.string2path

object Main {
  def main(args: Array[String]) {
    val javaFiles = (args(0) ** "*.java")
    println(javaFiles.size)
  }
}
```

with args(0) as a directory with around 300 java files in subdirectories produces StackOverFlowError with both 0.1.2 and 0.2.0-SNAPSHOT (scala 2.9.0-1 on Ubuntu 11.04):

``` pre
java.lang.StackOverflowError
    at java.lang.ThreadLocal.get(ThreadLocal.java:125)
    at java.lang.StringCoding.deref(StringCoding.java:46)
    at java.lang.StringCoding.decode(StringCoding.java:159)
    at java.lang.String.<init>(String.java:443)
    at java.lang.String.<init>(String.java:515)
    at java.io.UnixFileSystem.canonicalize0(Native Method)
    at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:157)
    at java.io.File.getCanonicalPath(File.java:559)
    at sun.security.provider.PolicyFile.canonPath(PolicyFile.java:1849)
    at java.io.FilePermission$1.run(FilePermission.java:186)
    at java.io.FilePermission$1.run(FilePermission.java:183)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.io.FilePermission.init(FilePermission.java:183)
    at java.io.FilePermission.<init>(FilePermission.java:249)
    at java.lang.SecurityManager.checkRead(SecurityManager.java:871)
    at java.io.File.isDirectory(File.java:752)
    at scalax.file.defaultfs.DefaultPath.isDirectory(DefaultPath.scala:57)
    at scalax.file.BasicPathSet$$anon$1.gd1$1(path-set.scala:169)
    at scalax.file.BasicPathSet$$anon$1.scalax$file$BasicPathSet$$anon$$loadNext(path-set.scala:167)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scala.Option.orElse(Option.scala:219)
    at scalax.file.BasicPathSet$$anon$1.scalax$file$BasicPathSet$$anon$$loadNext(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scala.Option.orElse(Option.scala:219)
    at scalax.file.BasicPathSet$$anon$1.scalax$file$BasicPathSet$$anon$$loadNext(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$1.apply(path-set.scala:175)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$1.apply(path-set.scala:175)
    at scala.Option.orElse(Option.scala:219)
    at scalax.file.BasicPathSet$$anon$1.scalax$file$BasicPathSet$$anon$$loadNext(path-set.scala:175)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scala.Option.orElse(Option.scala:219)
    at scalax.file.BasicPathSet$$anon$1.scalax$file$BasicPathSet$$anon$$loadNext(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scala.Option.orElse(Option.scala:219)
    at scalax.file.BasicPathSet$$anon$1.scalax$file$BasicPathSet$$anon$$loadNext(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scalax.file.BasicPathSet$$anon$1$$anonfun$scalax$file$BasicPathSet$$anon$$loadNext$2.apply(path-set.scala:178)
    at scala.Option.orElse(Option.scala:219)
...
```

**Comment by jesseeichar** [comment]
Closed as of 021e43c34196927acd2075e4a5645620a1ca83a6 thanks to mpelton's patch

**Comment by mpeltonen** [comment]
Thanks for the quick response! 

Does the snapshot in scala-tools.org update automatically? Any chance of getting 0.1.3 on the repo-releases with the fix?

**Comment by jesseeichar** [comment]
Sure.  for 2.9.0?

**Comment by jesseeichar** [comment]
I should also ask if you want it based on 0.1.2 or if you want it cut from trunk... although that is more going to be 0.2

**Comment by mpeltonen** [comment]
0.2.0-SNAPSHOT for 2.9.0-1 or 2.9.1 is fine, thx!

**Comment by jesseeichar** [comment]
Done a new snapshot is online.  2.9.1 has to wait for a new scala-arm build.  I am planning on either getting upload access to the scala-tool repo for arm or making my own fork so I don't have to wait for josh. Josh is good but I have limitted time and having to wait for others is a tough one.

**Comment by mpeltonen** [comment]
Yeah. Actually even your latest push does not work out of the box, because scala-arm 0.2 for 2.9.0-1 (or any version for 2.9.0-1) does not exist in any public repo (or at least at scala-tools.org).

**Comment by mpeltonen** [comment]
Meaning you have to add these both:

  "com.github.scala-incubator.io" % "scala-io-file_2.9.0-1" % "0.2.0-SNAPSHOT", 
  "com.github.jsuereth.scala-arm" % "scala-arm_2.9.0" % "0.2"

but I can continue my scala-io testing now, thx! :)

**Comment by jesseeichar** [comment]
Thanks for the information.  I will try to get ahold of josh and publish 2.9.0_1 and 2.9.1 builds
