### ISSUE TITLE
"com.github.scala-incubator.io" % "scala-io-core_2.10" % "0.4.1" is not binary compatible with scala 2.10

### ISSUE THREAD

**Issue by arturaz** [jesseeichar/scala-io#77]
```
java.lang.NoSuchMethodError: scala.LowPriorityImplicits.charWrapper(C)Lscala/runtime/RichChar;
    at scalax.file.FileSystem.<init>(FileSystem.scala:49)
    at scalax.file.defaultfs.DefaultFileSystem.<init>(DefaultFileSystem.scala:20)
    at scalax.file.FileSystem$.<init>(FileSystem.scala:34)
    at scalax.file.FileSystem$.<clinit>(FileSystem.scala)
    at scalax.file.Path$.apply(Path.scala:84)
    at app.PostcodeSet$.fromDirectory(PostcodeSet.scala:31)
```

When running with scala 2.10.

**Comment by jesseeichar** [comment]
To the best of my knowledge I compiled with 2.10.  But I will take another look.  Did you clear your sbt cache or maven of old scala-io 0.4.1 binaries and ivy information.  I found that I had to do that to make it work.

**Comment by arturaz** [comment]
```
$ rm -rf project/target/ target/ ~/.ivy2/cache/com.github.scala-incubator.io.*
$ sbt
> clean
[success] Total time: 0 s, completed Jan 7, 2013 4:30:28 PM
> test-only app.PostcodeSetTest
...
[error] Could not run test app.PostcodeSetTest: java.lang.NoSuchMethodError: scala.LowPriorityImplicits.charWrapper(C)Lscala/runtime/RichChar;
```

Then I removed 

```
 val ScalaIo = "0.4.1"
      "com.github.scala-incubator.io" % "scala-io-core_2.10" % V.ScalaIo,
      "com.github.scala-incubator.io" % "scala-io-file_2.10" % V.ScalaIo,
```

from my build and put freshly built scala-io-file_2.10.0-0.5.0-SNAPSHOT.jar & core into lib/ and everything went fine and dandy :)

**Comment by jesseeichar** [comment]
ok thanks for the update.  I will look into this.

**Comment by arturaz** [comment]
Thanks for the quick response :)

**Comment by jesseeichar** [comment]
I just did this:

```
 mv ~/.ivy2 ~/.ivy2_all
 curl -L http://jesseeichar.github.com/scala-io-doc/0.4.1/example_projects/example-sbt-project.zip >     tmp.zip && unzip tmp.zip && rm tmp.zip
 cd example-sbt-project
 sbt run
```

Could you see if this works for you because it works for me (and it uses scala 2.10.0).  If it works for you...

If that works then we need to make the example more complex.  If you have an idea how to change the example code or build.sbt to make it fail that would be a great help.

**Comment by arturaz** [comment]
Will do when I get home :-)

**Comment by arturaz** [comment]
Didn't get the chance to do this at home. However I did this at work and yes, it does work. I'll try sniffing around to see what causes problems on my side.

**Comment by arturaz** [comment]
Found it! The problem lies in typesafe repository.

I have `"Typesafe" at "http://repo.typesafe.com/typesafe/releases/"` in my resolvers list. 

When I added it to your examples build.sbt, things broke with same error message. I guess a broken artifact lies around in typesafe repository.

**Comment by jesseeichar** [comment]
It is probably an old scala-arm binary in the typesafe repository.

Good job! :)

**Comment by arturaz** [comment]
Can you remove it please ? ;)

**Comment by jesseeichar** [comment]
Sadly I don't have access to scala-arm binaries.  I will talk to Josh
Suereth about it.

**Comment by arturaz** [comment]
Great. Thanks!

As a workaround people can use 

```
        moduleConfigurations += ModuleConfiguration(
          "com.github.scala-incubator.io",
          DefaultMavenRepository
        )
```

for now.

**Comment by xuwei-k** [comment]
@jesseeichar please publish **new version** for Scala 2.10

https://github.com/playframework/Play20/pull/676#issuecomment-12353092
